### ISSUE TITLE
parse Wang2017

### ISSUE THREAD

**Issue by LeoPompidou** [monarch-initiative/IDGKG-gen#25]
Paper: 
https://www.cell.com/cell/fulltext/S0092-8674(17)30061-2?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867417300612%3Fshowall%3Dtrue

Should I use supplementary table S5 with the Ba/F3 cell data or the AML cell data provided in supplementary table S3?
What would be a good cutoff to decide between SL and not SL?

**Comment by pnrobinson** [comment]
@LeoPompidou  I am not sure that table S7 is correct, it seems to just contain the mouse data. I will try to figure out the paper, which has lots of information!

**Comment by pnrobinson** [comment]
Actually, there are 10 high confidence human SLIs in this paper. I wrote a class to enter the information manually.
