### ISSUE TITLE
Gene essentiality and synthetic lethality in haploid human cells.

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/IDGKG-gen#31]
https://pubmed.ncbi.nlm.nih.gov/26472760/

**Comment by pnrobinson** [comment]
This is starting to work but the NCBI Gene symbol to id is missing some genes even though the symbols are in the Gene file, e.g., 
COG3. Let's figure out how to get all of the genes, otherwise we will need to add the gene ids per hand, which would be ugly!

**Comment by LeoPompidou** [comment]
I will definitely have at look at this!

**Comment by vidarmehr** [comment]
@pnrobinson I found the gene ensembl identifier of COG3 in lookup/lookup.txt file. It is ENSG00000136152.

**Comment by pnrobinson** [comment]
Revised the code for this, it seems to be working now!
