### ISSUE TITLE
parse_STRING

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/IDGKG-gen#34]
I ran parse_STRING.py. The output files shows that non of the proteins were mapped to gene ensembles. Also, I think we should put a threshold(=700) on the scores and extract proteins with score > threshold.
@LeoPompidou Leo, have you tried running parse_STRING? Am I missing something?

**Comment by LeoPompidou** [comment]
That probabily had to do with the messed up lookup file. I loaded the fixed version to the branch parse_depmap and also added the cutoff you suggested!

**Comment by vidarmehr** [comment]
Ok. Thanks, Leo.
