### ISSUE TITLE
parse_synleth

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/IDGKG-gen#35]
How should I run parse_synleth? I receive the following error message when I run it:
Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/IDGKG-gen/parse_synleth.py", line 22, in <module>
    table = pd.read_csv(sys.argv[1], sep='\t')
IndexError: list index out of range

Process finished with exit code 1

**Comment by pnrobinson** [comment]
Not the correct file -- use parse_human_SLI.py (which itself still needs some work)
