### ISSUE TITLE
A Network of Conserved Synthetic Lethal Interactions for Exploration of Precision Cancer Therapy.

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/IDGKG-gen#6]
https://www.ncbi.nlm.nih.gov/pubmed/27453043

**Comment by justaddcoffee** [comment]
Interesting one - investigates specifically tumor suppressor genes and their possible SL partners.

Similar to others, they use phylogenetic conservation of these interactions in yeast/human to pare down their list of SL pairs

**Comment by pnrobinson** [comment]
Srivas et al.
Done
